apply plugin: "java"

version = '1.0'

sourceSets.main.java.srcDirs = ["src"]

def targetVersion = project.findProperty("mindustryVersion") ?: "v159.7"
def isDev = project.hasProperty("dev")

repositories{
    mavenCentral()

    if (targetVersion == "v147") {
        maven{ url = "https://raw.githubusercontent.com/Zelaux/MindustryRepo/master/repository" }
        maven{ url = 'https://www.jitpack.io' }
    }
    else {
        ivy{
            url = "https://github.com/"
            patternLayout{
                artifact(
                    (targetVersion == "latest"
                        ? "/[organisation]/[module]/releases/[revision]/download/dependencies.jar"
                        : targetVersion == "be"
                            ? "/[organisation]/[module]/releases/download/master/[revision].jar"
                            : "/[organisation]/[module]/releases/download/[revision]/dependencies.jar")
                )
            }

            metadataSources{
                artifact()
            }

            content{
                if(targetVersion == "be"){
                    includeVersion("Anuken", "MindustryBuilds", "latest")
                }else{
                    includeVersion("Anuken", "Mindustry", targetVersion)
                }
            }
        }
    }
}

java{
    targetCompatibility = JavaVersion.VERSION_17
    sourceCompatibility = JavaVersion.VERSION_17
}

ext{
    mindustryVersion = targetVersion
    if (targetVersion == "v147") { jabelVersion = "93fde537c7" }
    isWindows = System.getProperty("os.name").toLowerCase().contains("windows")
    sdkRoot = System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT")
}

allprojects{
    tasks.withType(JavaCompile).configureEach{
        if(!isDev){
            exclude "hao1337/addins/DevTools.java"
        }
    }
}

dependencies{
    if (targetVersion == "v147") {
        compileOnly "com.github.Anuken.Arc:arc-core:$mindustryVersion"
        compileOnly "com.github.Anuken.Mindustry:core:$mindustryVersion"

        annotationProcessor "com.github.Anuken:jabel:$jabelVersion"
    }
    else {
        compileOnly(
            mindustryVersion == "be"
                ? "Anuken:MindustryBuilds:latest"
                : "Anuken:Mindustry:$mindustryVersion"
        )
    }
}

if (targetVersion == "v147") {
    configurations.configureEach{
        resolutionStrategy.eachDependency { details ->
            if(details.requested.group == 'com.github.Anuken.Arc'){
                details.useVersion "$mindustryVersion"
            }
        }
    }
}

tasks.register('jarAndroid'){
    dependsOn "jar"

    doLast{
        if(!sdkRoot || !new File(sdkRoot).exists()) throw new GradleException("No valid Android SDK found. Ensure that ANDROID_HOME is set to your Android SDK directory.")

        def platformRoot = new File("$sdkRoot/platforms/").listFiles().sort().reverse().find{ f -> new File(f, "android.jar").exists() }

        if(!platformRoot) throw new GradleException("No android.jar found. Ensure that you have an Android platform installed.")

        //collect dependencies needed for desugaring
        def dependencies = (configurations.compileClasspath.asList() + configurations.runtimeClasspath.asList() + [new File(platformRoot, "android.jar")]).collect{ "--classpath $it.path" }.join(" ")

        def d8 = isWindows ? "d8.bat" : "d8"

        //dex and desugar files - this requires d8 in your PATH
        "$d8 $dependencies --min-api 14 --output ${project.name}-android.jar ${project.name}-desktop.jar"
                .execute(null, new File("build/libs")).waitForProcessOutput(System.out, System.err)
    }
}

tasks.register('printRuntimeClasspath') {
    doLast {
        println configurations.runtimeClasspath.asPath
    }
}
    
tasks.register('platformcleanup', Exec) {
    workingDir = file("scripts")
    commandLine "node", "platform-revert.ts"
}

tasks.register('preparev157', Exec) {
    workingDir = file("scripts")
    commandLine "node", "platform.ts", "v159.7"
}

tasks.register('preparev147', Exec) {
    workingDir = file("scripts")
    commandLine "node", "platform.ts", "v147"
}

jar{
    archiveFileName = "${project.name}-desktop.jar"

    from{
        configurations.runtimeClasspath.collect{ it.isDirectory() ? it : zipTree(it) }
    }

    from(projectDir){
        include "mod.hjson"
    }

    from("assets/"){
        include "**"
    }
}

tasks.register('deploy', Jar){
    dependsOn jarAndroid
    dependsOn jar
    archiveFileName = "${project.name}.jar"

    from{ [zipTree("build/libs/${project.name}-desktop.jar"), zipTree("build/libs/${project.name}-android.jar")] }

    doLast{
        delete{
            delete "build/libs/${project.name}-android.jar"
        }
    }
}

tasks.register("deployv147", GradleBuild) {
    tasks = ["preparev147", "deploy", "platformcleanup"]
    startParameter.projectProperties = [ mindustryVersion: "v147" ]
}

tasks.register("deployv157", GradleBuild) {
    tasks = ["preparev157", "deploy", "platformcleanup"]
    startParameter.projectProperties = [ mindustryVersion: "v159.7" ]
}