name: Build Mod

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - mindustry: v147
            prefix: steam-
          - mindustry: v154
            prefix: ""

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup NodeJS 24
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Setup Android build-tools
      run: echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

    - name: install npm
      run: npm ci

    - name: Build mod jar
      run: |
        chmod +x ./gradlew
        ./gradlew deploy${{ matrix.mindustry }} -PmindustryVersion=${{ matrix.mindustry }}
    
    - name: Check result
      run: ls -R build

    - name: Rename artifact
      run: |
        DES=build/libs/${{ matrix.prefix }}${{ github.event.repository.name }}.jar
          
        for f in build/libs/*.jar; do
          [[ "$f" == *-desktop.jar ]] && continue
          [ "$f" != "$DES" ] && mv "$f" "$DES"
          break
        done

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.mindustry }}
        path: build/libs/${{ matrix.prefix }}${{ github.event.repository.name }}.jar